/****************************************************************************
*   Generated by ACUITY 6.6.1
*   Match ovxlib 1.1.35
*
*   Neural Network appliction network definition source file
****************************************************************************/
/*-------------------------------------------
                   Includes
 -------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>

#include "vsi_nn_pub.h"

#include "vnn_global.h"
#include "vnn_mnist.h"

/*-------------------------------------------
                   Macros
 -------------------------------------------*/

#define NEW_VXNODE(_node, _type, _in, _out, _uid) do {\
        _node = vsi_nn_AddNode( graph, _type, _in, _out, NULL );\
        if( NULL == _node ) {\
            goto error;\
        }\
        _node->uid = (uint32_t)_uid;\
    } while(0)

#define NEW_VIRTUAL_TENSOR(_id, _attr, _dtype) do {\
        memset( _attr.size, 0, VSI_NN_MAX_DIM_NUM * sizeof(vsi_size_t));\
        _attr.dim_num = VSI_NN_DIM_AUTO;\
        _attr.vtl = !VNN_APP_DEBUG;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set const tensor dims out of this macro.
#define NEW_CONST_TENSOR(_id, _attr, _dtype, _ofst, _size) do {\
        data = load_data( fp, _ofst, _size  );\
        _attr.vtl = FALSE;\
        _attr.is_const = TRUE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, data );\
        free( data );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set generic tensor dims out of this macro.
#define NEW_NORM_TENSOR(_id, _attr, _dtype) do {\
        _attr.vtl = FALSE;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set generic tensor dims out of this macro.
#define NEW_NORM_TENSOR_FROM_HANDLE(_id, _attr, _dtype) do {\
        _attr.vtl = FALSE;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensorFromHandle( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

#define NET_NODE_NUM            (9)
#define NET_NORM_TENSOR_NUM     (2)
#define NET_CONST_TENSOR_NUM    (8)
#define NET_VIRTUAL_TENSOR_NUM  (9)
#define NET_TOTAL_TENSOR_NUM    (NET_NORM_TENSOR_NUM + NET_CONST_TENSOR_NUM + NET_VIRTUAL_TENSOR_NUM)

/*-------------------------------------------
               Local Variables
 -------------------------------------------*/

/*-------------------------------------------
                  Functions
 -------------------------------------------*/
static uint8_t* load_data
    (
    FILE  * fp,
    size_t  ofst,
    size_t  sz
    )
{
    uint8_t* data;
    int32_t ret;
    data = NULL;
    if( NULL == fp )
    {
        return NULL;
    }

    ret = VSI_FSEEK(fp, ofst, SEEK_SET);
    if (ret != 0)
    {
        VSILOGE("blob seek failure.");
        return NULL;
    }

    data = (uint8_t*)malloc(sz);
    if (data == NULL)
    {
        VSILOGE("buffer malloc failure.");
        return NULL;
    }
    ret = fread(data, 1, sz, fp);
    return data;
} /* load_data() */

vsi_nn_graph_t * vnn_CreateMnist
    (
    const char * data_file_name,
    vsi_nn_context_t in_ctx,
    const vsi_nn_preprocess_map_element_t * pre_process_map,
    uint32_t pre_process_map_count,
    const vsi_nn_postprocess_map_element_t * post_process_map,
    uint32_t post_process_map_count
    )
{
    uint32_t                _infinity = VSI_NN_FLOAT32_INF;
    vsi_status              status;
    vsi_bool                release_ctx;
    vsi_nn_context_t        ctx;
    vsi_nn_graph_t *        graph;
    vsi_nn_node_t *         node[NET_NODE_NUM];
    vsi_nn_tensor_id_t      norm_tensor[NET_NORM_TENSOR_NUM];
    vsi_nn_tensor_id_t      const_tensor[NET_CONST_TENSOR_NUM];
    vsi_nn_tensor_attr_t    attr;
    FILE *                  fp;
    uint8_t *               data;
    uint32_t                i = 0;
    char *                  use_img_process_s;
    int32_t                 enable_pre_post_process = 0;
    vsi_bool                sort = FALSE;
    vsi_bool                inference_with_nbg = FALSE;
    char*                   pos = NULL;

    vsi_size_t shape_1[] = { -1, 1 };




    (void)(_infinity);
    ctx = NULL;
    graph = NULL;
    status = VSI_FAILURE;
    memset( &attr, 0, sizeof( attr ) );
    memset( &node, 0, sizeof( vsi_nn_node_t * ) * NET_NODE_NUM );

    fp = fopen( data_file_name, "rb" );
    if( NULL == fp )
    {
        VSILOGE( "Open file %s failed.", data_file_name );
        goto error;
    }

    pos = strstr(data_file_name, ".nb");
    if( pos && strcmp(pos, ".nb") == 0 )
    {
        inference_with_nbg = TRUE;
    }

    if( NULL == in_ctx )
    {
        ctx = vsi_nn_CreateContext();
    }
    else
    {
        ctx = in_ctx;
    }

    use_img_process_s = getenv( "VSI_USE_IMAGE_PROCESS" );
    if( use_img_process_s )
    {
        enable_pre_post_process = atoi(use_img_process_s);
    }

    graph = vsi_nn_CreateGraph( ctx, NET_TOTAL_TENSOR_NUM, NET_NODE_NUM );
    if( NULL == graph )
    {
        VSILOGE( "Create graph fail." );
        goto error;
    }
    vsi_nn_SetGraphVersion( graph, VNN_VERSION_MAJOR, VNN_VERSION_MINOR, VNN_VERSION_PATCH );
    vsi_nn_SetGraphInputs( graph, NULL, 1 );
    vsi_nn_SetGraphOutputs( graph, NULL, 1 );

/*-----------------------------------------
  Register client ops
 -----------------------------------------*/


/*-----------------------------------------
  Node definitions
 -----------------------------------------*/
    if( !inference_with_nbg )
    {

    /*-----------------------------------------
      lid       - Conv_/conv1/conv1.0/Conv_9
      var       - node[0]
      name      - Conv_/conv1/conv1.0/Conv
      operation - convolution
      input     - [28, 28, 1, 1]
      filter    - [5, 5, 1, 10]
      output    - [24, 24, 10, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[0], VSI_NN_OP_CONV2D, 3, 1, 9);
    node[0]->nn_param.conv2d.ksize[0] = 5;
    node[0]->nn_param.conv2d.ksize[1] = 5;
    node[0]->nn_param.conv2d.weights = 10;
    node[0]->nn_param.conv2d.stride[0] = 1;
    node[0]->nn_param.conv2d.stride[1] = 1;
    node[0]->nn_param.conv2d.pad[0] = 0;
    node[0]->nn_param.conv2d.pad[1] = 0;
    node[0]->nn_param.conv2d.pad[2] = 0;
    node[0]->nn_param.conv2d.pad[3] = 0;
    node[0]->nn_param.conv2d.group = 1;
    node[0]->nn_param.conv2d.dilation[0] = 1;
    node[0]->nn_param.conv2d.dilation[1] = 1;
    node[0]->nn_param.conv2d.multiplier = 0;
    node[0]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[0]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_NEAREST_EVEN;
    node[0]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Relu_/conv1/conv1.1/Relu_8
      var       - node[1]
      name      - Relu_/conv1/conv1.1/Relu
      operation - relu
      input     - [24, 24, 10, 1]
      output    - [24, 24, 10, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[1], VSI_NN_OP_RELU, 1, 1, 8);

    /*-----------------------------------------
      lid       - MaxPool_/conv1/conv1.2/MaxPool_7
      var       - node[2]
      name      - MaxPool_/conv1/conv1.2/MaxPool
      operation - pooling
      input     - [24, 24, 10, 1]
      output    - [12, 12, 10, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[2], VSI_NN_OP_POOL, 1, 1, 7);
    node[2]->nn_param.pool.ksize[0] = 2;
    node[2]->nn_param.pool.ksize[1] = 2;
    node[2]->nn_param.pool.stride[0] = 2;
    node[2]->nn_param.pool.stride[1] = 2;
    node[2]->nn_param.pool.pad[0] = 0;
    node[2]->nn_param.pool.pad[1] = 0;
    node[2]->nn_param.pool.pad[2] = 0;
    node[2]->nn_param.pool.pad[3] = 0;
    node[2]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[2]->nn_param.pool.round_type = VSI_NN_ROUND_FLOOR;
    node[2]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Conv_/conv2/conv2.0/Conv_6
      var       - node[3]
      name      - Conv_/conv2/conv2.0/Conv
      operation - convolution
      input     - [12, 12, 10, 1]
      filter    - [5, 5, 10, 20]
      output    - [8, 8, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[3], VSI_NN_OP_CONV2D, 3, 1, 6);
    node[3]->nn_param.conv2d.ksize[0] = 5;
    node[3]->nn_param.conv2d.ksize[1] = 5;
    node[3]->nn_param.conv2d.weights = 20;
    node[3]->nn_param.conv2d.stride[0] = 1;
    node[3]->nn_param.conv2d.stride[1] = 1;
    node[3]->nn_param.conv2d.pad[0] = 0;
    node[3]->nn_param.conv2d.pad[1] = 0;
    node[3]->nn_param.conv2d.pad[2] = 0;
    node[3]->nn_param.conv2d.pad[3] = 0;
    node[3]->nn_param.conv2d.group = 1;
    node[3]->nn_param.conv2d.dilation[0] = 1;
    node[3]->nn_param.conv2d.dilation[1] = 1;
    node[3]->nn_param.conv2d.multiplier = 0;
    node[3]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[3]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_NEAREST_EVEN;
    node[3]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Relu_/conv2/conv2.1/Relu_5
      var       - node[4]
      name      - Relu_/conv2/conv2.1/Relu
      operation - relu
      input     - [8, 8, 20, 1]
      output    - [8, 8, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[4], VSI_NN_OP_RELU, 1, 1, 5);

    /*-----------------------------------------
      lid       - MaxPool_/conv2/conv2.2/MaxPool_4
      var       - node[5]
      name      - MaxPool_/conv2/conv2.2/MaxPool
      operation - pooling
      input     - [8, 8, 20, 1]
      output    - [4, 4, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[5], VSI_NN_OP_POOL, 1, 1, 4);
    node[5]->nn_param.pool.ksize[0] = 2;
    node[5]->nn_param.pool.ksize[1] = 2;
    node[5]->nn_param.pool.stride[0] = 2;
    node[5]->nn_param.pool.stride[1] = 2;
    node[5]->nn_param.pool.pad[0] = 0;
    node[5]->nn_param.pool.pad[1] = 0;
    node[5]->nn_param.pool.pad[2] = 0;
    node[5]->nn_param.pool.pad[3] = 0;
    node[5]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[5]->nn_param.pool.round_type = VSI_NN_ROUND_FLOOR;
    node[5]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Reshape_/Reshape_3
      var       - node[6]
      name      - Reshape_/Reshape
      operation - reshape
      input     - [4, 4, 20, 1]
      output    - [320, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[6], VSI_NN_OP_RESHAPE2, 1, 1, 3);
    node[6]->nn_param.reshape2.size = shape_1;
    node[6]->nn_param.reshape2.dim_num = 2;

    /*-----------------------------------------
      lid       - Gemm_/fc/fc.0/Gemm_2
      var       - node[7]
      name      - Gemm_/fc/fc.0/Gemm
      operation - fullconnect
      input     - [320, 1]
      filter    - [320, 50]
      output    - [50, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[7], VSI_NN_OP_FCL, 3, 1, 2);
    node[7]->nn_param.fcl.weights = 50;
    node[7]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[7]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_NEAREST_EVEN;
    node[7]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Gemm_/fc/fc.1/Gemm_1
      var       - node[8]
      name      - Gemm_/fc/fc.1/Gemm
      operation - fullconnect
      input     - [50, 1]
      filter    - [50, 10]
      output    - [10, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[8], VSI_NN_OP_FCL, 3, 1, 1);
    node[8]->nn_param.fcl.weights = 10;
    node[8]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[8]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_NEAREST_EVEN;
    node[8]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    }
    else
    {
    NEW_VXNODE(node[0], VSI_NN_OP_NBG, 1, 1, 0);
    node[0]->nn_param.nbg.type = VSI_NN_NBG_FILE;
    node[0]->nn_param.nbg.url = data_file_name;

    }

/*-----------------------------------------
  Tensor initialize
 -----------------------------------------*/
    attr.dtype.fmt = VSI_NN_DIM_FMT_NCHW;
    /* @attach_Gemm_/fc/fc.1/Gemm/out0_0:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 10;
    attr.size[1] = 1;
    attr.dim_num = 2;
    attr.dtype.scale = 30.181732177734375;
    attr.dtype.zero_point = 78;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_NORM_TENSOR(norm_tensor[0], attr, VSI_NN_TYPE_UINT8);

    /* @input_10:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 28;
    attr.size[1] = 28;
    attr.size[2] = 1;
    attr.size[3] = 1;
    attr.dim_num = 4;
    attr.dtype.scale = 3.2457001209259033;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_NORM_TENSOR(norm_tensor[1], attr, VSI_NN_TYPE_UINT8);



    if( !inference_with_nbg )
    {
    /* @Conv_/conv1/conv1.0/Conv_9:weight */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 5;
    attr.size[1] = 5;
    attr.size[2] = 1;
    attr.size[3] = 10;
    attr.dim_num = 4;
    attr.dtype.scale = 0.0035130344331264496;
    attr.dtype.zero_point = 122;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[0], attr, VSI_NN_TYPE_UINT8, 40, 250);

    /* @Conv_/conv1/conv1.0/Conv_9:bias */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 10;
    attr.dim_num = 1;
    attr.dtype.scale = 0.011402255855500698;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[1], attr, VSI_NN_TYPE_INT32, 0, 40);

    /* @Conv_/conv2/conv2.0/Conv_6:weight */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 5;
    attr.size[1] = 5;
    attr.size[2] = 10;
    attr.size[3] = 20;
    attr.dim_num = 4;
    attr.dtype.scale = 0.0020445496775209904;
    attr.dtype.zero_point = 135;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[2], attr, VSI_NN_TYPE_UINT8, 370, 5000);

    /* @Conv_/conv2/conv2.0/Conv_6:bias */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 20;
    attr.dim_num = 1;
    attr.dtype.scale = 0.02001633308827877;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[3], attr, VSI_NN_TYPE_INT32, 290, 80);

    /* @Gemm_/fc/fc.0/Gemm_2:weight */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 320;
    attr.size[1] = 50;
    attr.dim_num = 2;
    attr.dtype.scale = 0.0013230362674221396;
    attr.dtype.zero_point = 131;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[4], attr, VSI_NN_TYPE_UINT8, 5570, 16000);

    /* @Gemm_/fc/fc.0/Gemm_2:bias */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 50;
    attr.dim_num = 1;
    attr.dtype.scale = 0.013041947036981583;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[5], attr, VSI_NN_TYPE_INT32, 5370, 200);

    /* @Gemm_/fc/fc.1/Gemm_1:weight */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 50;
    attr.size[1] = 10;
    attr.dim_num = 2;
    attr.dtype.scale = 0.0029082621913403273;
    attr.dtype.zero_point = 118;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[6], attr, VSI_NN_TYPE_UINT8, 21610, 500);

    /* @Gemm_/fc/fc.1/Gemm_1:bias */
    memset( &attr, 0, sizeof( attr ) );
    attr.size[0] = 10;
    attr.dim_num = 1;
    attr.dtype.scale = 0.0540536604821682;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[7], attr, VSI_NN_TYPE_INT32, 21570, 40);



    /* @Conv_/conv1/conv1.0/Conv_9:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 9.790093421936035;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[0]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Relu_/conv1/conv1.1/Relu_8:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 9.790093421936035;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[1]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @MaxPool_/conv1/conv1.2/MaxPool_7:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 9.790093421936035;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[2]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Conv_/conv2/conv2.0/Conv_6:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 9.857588768005371;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[3]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Relu_/conv2/conv2.1/Relu_5:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 9.857588768005371;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[4]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @MaxPool_/conv2/conv2.2/MaxPool_4:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 9.857588768005371;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[5]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Reshape_/Reshape_3:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 9.857588768005371;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[6]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Gemm_/fc/fc.0/Gemm_2:out0 */
    memset( &attr, 0, sizeof( attr ) );
    attr.dtype.scale = 18.586240768432617;
    attr.dtype.zero_point = 100;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[7]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);



/*-----------------------------------------
  Connection initialize
 -----------------------------------------*/
    node[0]->input.tensors[0] = norm_tensor[1];
    node[8]->output.tensors[0] = norm_tensor[0];

    /* Conv_/conv1/conv1.0/Conv_9 */
    node[0]->input.tensors[1] = const_tensor[0]; /* data_weight */
    node[0]->input.tensors[2] = const_tensor[1]; /* data_bias */

    /* Relu_/conv1/conv1.1/Relu_8 */
    node[1]->input.tensors[0] = node[0]->output.tensors[0];

    /* MaxPool_/conv1/conv1.2/MaxPool_7 */
    node[2]->input.tensors[0] = node[1]->output.tensors[0];

    /* Conv_/conv2/conv2.0/Conv_6 */
    node[3]->input.tensors[0] = node[2]->output.tensors[0];
    node[3]->input.tensors[1] = const_tensor[2]; /* data_weight */
    node[3]->input.tensors[2] = const_tensor[3]; /* data_bias */

    /* Relu_/conv2/conv2.1/Relu_5 */
    node[4]->input.tensors[0] = node[3]->output.tensors[0];

    /* MaxPool_/conv2/conv2.2/MaxPool_4 */
    node[5]->input.tensors[0] = node[4]->output.tensors[0];

    /* Reshape_/Reshape_3 */
    node[6]->input.tensors[0] = node[5]->output.tensors[0];

    /* Gemm_/fc/fc.0/Gemm_2 */
    node[7]->input.tensors[0] = node[6]->output.tensors[0];
    node[7]->input.tensors[1] = const_tensor[4]; /* data_weight */
    node[7]->input.tensors[2] = const_tensor[5]; /* data_bias */

    /* Gemm_/fc/fc.1/Gemm_1 */
    node[8]->input.tensors[0] = node[7]->output.tensors[0];
    node[8]->input.tensors[1] = const_tensor[6]; /* data_weight */
    node[8]->input.tensors[2] = const_tensor[7]; /* data_bias */


    }
    else
    {
    node[0]->output.tensors[0] = norm_tensor[0];
    node[0]->input.tensors[0] = norm_tensor[1];

    }
    graph->output.tensors[0] = norm_tensor[0];
    graph->input.tensors[0] = norm_tensor[1];


    if( enable_pre_post_process )
    {
        sort = TRUE;
        if( pre_process_map_count > 0 )
        {
            for( i = 0; i < pre_process_map_count; i++ )
            {
                status = vsi_nn_AddGraphPreProcess(graph, pre_process_map[i].graph_input_idx,
                                                   pre_process_map[i].preprocesses,
                                                   pre_process_map[i].preprocess_count);
                TEST_CHECK_STATUS( status, error );
            }
        }

        if( post_process_map_count > 0 )
        {
            for( i = 0; i < post_process_map_count; i++ )
            {
                 status = vsi_nn_AddGraphPostProcess(graph, post_process_map[i].graph_output_idx,
                                                     post_process_map[i].postprocesses,
                                                     post_process_map[i].postprocess_count);
                 TEST_CHECK_STATUS( status, error );
            }
        }
    }

    status = vsi_nn_SetupGraph( graph, sort );
    TEST_CHECK_STATUS( status, error );
    vsi_nn_DumpGraphToJson( graph );

    if( VSI_FAILURE == status )
    {
        goto error;
    }

    fclose( fp );

    return graph;

error:
    if( NULL != fp )
    {
        fclose( fp );
    }

    release_ctx = ( NULL == in_ctx );
    vsi_nn_DumpGraphToJson( graph );
    vnn_ReleaseMnist( graph, release_ctx );

    return NULL;
} /* vsi_nn_CreateMnist() */

void vnn_ReleaseMnist
    (
    vsi_nn_graph_t * graph,
    vsi_bool release_ctx
    )
{
    vsi_nn_context_t ctx;
    if( NULL != graph )
    {
        ctx = graph->ctx;
        vsi_nn_ReleaseGraph( &graph );

        /*-----------------------------------------
        Unregister client ops
        -----------------------------------------*/
        

        if( release_ctx )
        {
            vsi_nn_ReleaseContext( &ctx );
        }
    }
} /* vsi_nn_ReleaseMnist() */

